-- add_movies.sql

USE `movie_app`;

INSERT INTO `movies` (`title`, `description`, `release_year`, `genre`, `poster_url`) VALUES
('The Shawshank Redemption',
 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
 1994, 'Drama/Crime',
 'https://upload.wikimedia.org/wikipedia/en/8/81/ShawshankRedemptionMoviePoster.jpg'),
('The Godfather',
 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.',
 1972, 'Crime/Drama',
 'https://upload.wikimedia.org/wikipedia/en/1/1c/Godfather_ver1.jpg'),
('Pulp Fiction',
 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
 1994, 'Crime/Drama',
 'https://upload.wikimedia.org/wikipedia/en/8/82/Pulp_Fiction_cover.jpg'),
('Forrest Gump',
 'The presidencies of Kennedy and Johnson, the Vietnam War, Watergate, and other history unfold through the perspective of an Alabama man with an IQ of 75.',
 1994, 'Drama/Romance',
 'https://upload.wikimedia.org/wikipedia/en/6/67/Forrest_Gump_poster.jpg'),
('The Dark Knight',
 'When the menace known as the Joker wreaks havoc, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
 2008, 'Action/Drama',
 'https://upload.wikimedia.org/wikipedia/en/8/8a/Dark_Knight.jpg'),
('Fight Club',
 'An insomniac office worker and a soap maker form an underground fight club that evolves into something much more.',
 1999, 'Drama',
 'https://upload.wikimedia.org/wikipedia/en/f/fc/Fight_Club_poster.jpg'),
('The Lord of the Rings: The Fellowship of the Ring',
 'A meek Hobbit and eight companions set out on a journey to destroy the One Ring and save Middle-earth from the Dark Lord Sauron.',
 2001, 'Adventure/Fantasy',
 'https://upload.wikimedia.org/wikipedia/en/0/0c/The_Fellowship_of_the_Ring_%282001%29_theatrical_poster.jpg'),
('The Lord of the Rings: The Two Towers',
 'While Frodo and Sam edge closer to Mordor, the divided fellowship makes a stand against Sauron’s new ally, Saruman, and his army of Isengard.',
 2002, 'Adventure/Fantasy',
 'https://upload.wikimedia.org/wikipedia/en/a/ad/The_Two_Towers_poster.jpeg'),
('The Lord of the Rings: The Return of the King',
 'Gandalf and Aragorn lead the World of Men against Sauron’s army while Frodo and Sam approach Mount Doom to destroy the One Ring.',
 2003, 'Adventure/Fantasy',
 'https://upload.wikimedia.org/wikipedia/en/9/9d/Return_of_the_King_poster.jpg'),
('Star Wars: Episode IV – A New Hope',
 'Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee, and two droids to save the galaxy from the Empire’s world-destroying battle station.',
 1977, 'Sci-Fi/Adventure',
 'https://upload.wikimedia.org/wikipedia/en/8/87/StarWarsMoviePoster1977.jpg'),
('Titanic',
 'A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.',
 1997, 'Drama/Romance',
 'https://upload.wikimedia.org/wikipedia/en/2/22/Titanic_poster.jpg'),
('Jurassic Park',
 'A pragmatic paleontologist visiting an almost complete theme park is tasked with protecting a couple of kids after a power failure causes the park’s cloned dinosaurs to run loose.',
 1993, 'Adventure/Sci-Fi',
 'https://upload.wikimedia.org/wikipedia/en/e/e7/Jurassic_Park_poster.jpg'),
('The Lion King',
 'Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.',
 1994, 'Animation/Adventure',
 'https://upload.wikimedia.org/wikipedia/en/3/3d/The_Lion_King_poster.jpg'),
('The Avengers',
 'Earth’s mightiest heroes must come together and learn to fight as a team to stop the mischievous Loki and his alien army from enslaving humanity.',
 2012, 'Action/Sci-Fi',
 'https://upload.wikimedia.org/wikipedia/en/f/f9/TheAvengers2012Poster.jpg'),
('Avatar',
 'A paraplegic Marine is dispatched to the moon Pandora on a unique mission but becomes torn between following orders and protecting an alien civilization.',
 2009, 'Action/Adventure',
 'https://upload.wikimedia.org/wikipedia/en/b/b0/Avatar-Teaser-Poster.jpg'),
('Gladiator',
 'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.',
 2000, 'Action/Drama',
 'https://upload.wikimedia.org/wikipedia/en/8/8d/Gladiator_ver1.jpg'),
('The Prestige',
 'After a tragic accident, two stage magicians engage in a battle to create the ultimate illusion, with deadly consequences.',
 2006, 'Drama/Mystery',
 'https://upload.wikimedia.org/wikipedia/en/9/9b/Prestige_poster.jpg'),
('The Departed',
 'An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.',
 2006, 'Crime/Thriller',
 'https://upload.wikimedia.org/wikipedia/en/5/50/Departed_poster.jpg'),
('Whiplash',
 'A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student’s potential.',
 2014, 'Drama/Music',
 'https://upload.wikimedia.org/wikipedia/en/0/01/WhiplashPoster.jpg'),
('La La Land',
 'While navigating their careers in Los Angeles, a pianist and an actress fall in love but struggle to maintain their relationship as they chase their dreams.',
 2016, 'Comedy/Drama',
 'https://upload.wikimedia.org/wikipedia/en/a/ab/La_La_Land_%28film%29.png');
